name: Hotfix release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
        type: string

jobs:
  hotfix-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ inputs.branch }}
          regex: '^/hotfix\/(.*?)$'

      - uses: ./.github/workflows/service-release.yaml
        with:
          ref: ${{ github.event.inputs.branch }}
          tag: ${{ steps.regex-match.outputs.group1 }}
