name: release check
on:
  workflow_call:
  pull_request:
    types:
      - labeled

jobs:
  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@v1.8
