name: release

on:
  workflow_call:
    inputs:
      bump_level:
        description: 'Bump level'
        required: true
        type: string
      changelogConfigurationJson:
        description: 'Configuration for changelog builder'
        type: string
        required: false
        default: |
            {
              "template": "#{{CHANGELOG}}\n\n## Uncategorized\n\n#{{UNCATEGORIZED}}",
              "pr_template": "- #{{TITLE}} : #{{URL}} by @#{{AUTHOR}}",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }
  workflow_dispatch:
    inputs:
      bump_level:
        description: 'Bump level'
        required: true
        default: 'patch'
        type: choice
        options:
          - 'major'
          - 'minor'
          - 'patch'


jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: latest-release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"

      - name: Get next versions
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.latest-release.outputs.tag_name }}

      # Bump version on merging Pull Requests with specific labels.
      # (bump:major,bump:minor,bump:patch)
      - id: bumpr
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: haya14busa/action-bumpr@v1.8

      # Get tag name.
      - id: tag
        uses: haya14busa/action-cond@v1.1.1
        with:
          cond: "${{ startsWith(github.ref, 'refs/tags/') }}"
          if_true: ${{ github.ref_name }}
          if_false: ${{ format('steps.semvers.outputs.v_{0}', inputs.bump_level) }}

      - uses: haya14busa/action-update-semver@v1
        if: github.event_name == 'workflow_dispatch'
        with:
          github_token: ${{ secrets.github_token }}
          tag: ${{ steps.tag.outputs.value }}

      # https://github.com/mikepenz/release-changelog-builder-action#configuration
      - name: Build Changelog
        if: "!steps.bumpr.outputs.skip || startsWith(github.ref, 'refs/tags/')"
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: ${{ steps.bumpr.outputs.current_version }}
          toTag: ${{ steps.tag.outputs.value }}
          ignorePreReleases: true
          configurationJson: ${{ inputs.changelogConfigurationJson }}


      # Create release.
      - name: Release
        if: "!steps.bumpr.outputs.skip || startsWith(github.ref, 'refs/tags/')"
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          body: ${{ steps.build_changelog.outputs.changelog }}
