name: service release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Tag for the release'
        type: string
        required: false
        default: ""
      ref:
        description: 'Ref for the release'
        type: string
        required: false
        default: "main"
      changelogConfigurationJson:
        description: 'Configuration for changelog builder'
        type: string
        required: false
        default: |
            {
              "template": "#{{CHANGELOG}}\n\n## Uncategorized\n\n#{{UNCATEGORIZED}}",
              "pr_template": "- #{{TITLE}} : #{{URL}} by @#{{AUTHOR}}",
              "categories": [
                {
                    "title": "## 💬 Other",
                    "labels": ["other"]
                },
                {
                    "title": "## 📦 Dependencies",
                    "labels": ["dependencies"]
                }
              ]
            }

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for the release'
        type: string
        required: false
        default: ""

permissions: write-all
jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.ref }}
          fetch-depth: 0

      # get latest tag
      - id: latest-release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"

      - name: 'Get next minor version'
        id: semvers
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.latest-release.outputs.tag_name }}

      # get latest prerelease
      - id: latest-prerelease
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|release"

      - name: Get current datetime
        id: datetime
        run: echo "value=$(date +'%Y%m%d-%H%M%S')" >> "${GITHUB_OUTPUT}"
        env:
          TZ: Asia/Tokyo

      - id: cond
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ steps.latest-release.outputs.tag_name != '' }}"
          if_true: "${{ steps.semvers.outputs.v_patch }}-${{ steps.datetime.outputs.value }}"
          if_false: "v0.0.1-${{ steps.datetime.outputs.value }}"

      - id: tag
        uses: haya14busa/action-cond@v1
        with:
          cond: "${{ inputs.tag != '' }}"
          if_true: "${{ inputs.tag }}"
          if_false: "${{ steps.cond.outputs.value }}"

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ steps.tag.outputs.value }}
          tag_exists_error: false

      # https://github.com/mikepenz/release-changelog-builder-action#configuration
      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          fromTag: ${{ steps.latest-prerelease.outputs.tag_name }}
          toTag: ${{ steps.tag.outputs.value }}
          ignorePreReleases: false
          configurationJson: ${{ inputs.changelogConfigurationJson }}

      # Create release.
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.value }}
          body: ${{ steps.build_changelog.outputs.changelog }}
          prerelease: true
